# Build stage
FROM node:18.18.0-alpine AS builder
WORKDIR /app
COPY package.json yarn.lock ./
COPY packages/frontend/happy-quokka-nextjs ./packages/frontend/happy-quokka-nextjs
RUN yarn set version berry
RUN yarn install
RUN yarn workspace happy-quokka-nextjs build

# Production stage
FROM node:18.18.0-alpine
WORKDIR /app
COPY --from=builder /app .
EXPOSE 3000
CMD ["yarn", "workspace", "happy-quokka-nextjs", "start"]