FROM node:18.18.0-alpine
WORKDIR /app
COPY package.json yarn.lock ./
COPY packages/backend ./packages/backend/
RUN yarn set version berry
RUN yarn install

EXPOSE 8080
CMD ["yarn", "workspace", "backend", "start"]