name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::527409817429:role/eksClusterRole
        aws-region: eu-west-3

    - name: Set up kubectl
      uses: steebchen/kubectl@v1
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Deploy to EKS
      run: |
        kubectl apply -f ./k8s/web-ui-deployment.yaml
        kubectl apply -f ./k8s/web-ui-service.yaml
        kubectl apply -f ./k8s/api-deployment.yaml
        kubectl apply -f ./k8s/api-service.yaml